"""add performance indexes

Revision ID: 118c2a5eaa7d
Revises: f9c69a49f544
Create Date: 2026-06-15 20:15:44.076888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118c2a5eaa7d'
down_revision = 'f9c69a49f544'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.create_index('idx_hosts_inbound_tag', ['inbound_tag'], unique=False)
        batch_op.create_index('idx_hosts_is_disabled', ['is_disabled'], unique=False)

    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.create_index('idx_nodes_status', ['status'], unique=False)

    with op.batch_alter_table('notification_reminders', schema=None) as batch_op:
        batch_op.create_index('idx_notification_reminders_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_status_expire', ['status', 'expire'], unique=False)
        batch_op.create_index('idx_users_status_used_traffic', ['status', 'used_traffic'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_status_used_traffic')
        batch_op.drop_index('idx_users_status_expire')

    with op.batch_alter_table('notification_reminders', schema=None) as batch_op:
        batch_op.drop_index('idx_notification_reminders_user_id')

    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_index('idx_nodes_status')

    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.drop_index('idx_hosts_is_disabled')
        batch_op.drop_index('idx_hosts_inbound_tag')

    # ### end Alembic commands ###
