"""add admin otp columns

Revision ID: 177f1748895a
Revises: 797420faec8d
Create Date: 2025-11-08 13:29:54.741581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177f1748895a'
down_revision = '797420faec8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('otp_enabled', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('admins', sa.Column('otp_secret', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'otp_secret')
    op.drop_column('admins', 'otp_enabled')
    # ### end Alembic commands ###
