"""use bigint for id column

Revision ID: 4f15c0789493
Revises: 5213b80a795c
Create Date: 2026-02-15 10:41:49.611553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f15c0789493'
down_revision = '5213b80a795c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # CRITICAL: Process parent tables BEFORE child tables with foreign keys
    # to avoid foreign key constraint errors
    
    # Step 1: Parent tables (no foreign keys to other tables)
    with op.batch_alter_table('admins') as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False,
                   autoincrement=True)
    
    with op.batch_alter_table('core_configs') as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False,
                   autoincrement=True)
    
    with op.batch_alter_table('groups') as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False,
                   autoincrement=True)
    
    with op.batch_alter_table('hosts') as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False,
                   autoincrement=True)
    
    with op.batch_alter_table('inbounds') as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False,
                   autoincrement=True)
    
    with op.batch_alter_table('user_templates') as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False,
                   autoincrement=True)
    
    with op.batch_alter_table('settings') as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False,
                   autoincrement=True)
    
    with op.batch_alter_table('system') as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False,
                   autoincrement=True)
    
    # Step 2: Nodes table (references core_configs)
    with op.batch_alter_table('nodes') as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False,
                   autoincrement=True)
        batch_op.alter_column('core_config_id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=True)
    
    # Step 3: Users table (references admins)
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False,
                   autoincrement=True)
        batch_op.alter_column('admin_id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=True)
    
    # Step 4: Child tables (reference admins, users, nodes, groups, etc.)
    with op.batch_alter_table('admin_usage_logs') as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False,
                   autoincrement=True)
        batch_op.alter_column('admin_id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False)
    
    with op.batch_alter_table('inbounds_groups_association') as batch_op:
        batch_op.alter_column('inbound_id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False)
        batch_op.alter_column('group_id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False)
    
    with op.batch_alter_table('next_plans') as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False,
                   autoincrement=True)
        batch_op.alter_column('user_id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False)
        batch_op.alter_column('user_template_id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=True)
    
    with op.batch_alter_table('node_stats') as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False,
                   autoincrement=True)
        batch_op.alter_column('node_id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False)
    
    with op.batch_alter_table('node_usage_reset_logs') as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False,
                   autoincrement=True)
        batch_op.alter_column('node_id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False)
    
    with op.batch_alter_table('node_usages') as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False,
                   autoincrement=True)
        batch_op.alter_column('node_id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=True)
    
    with op.batch_alter_table('node_user_usages') as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False,
                   autoincrement=True)
        batch_op.alter_column('user_id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False)
        batch_op.alter_column('node_id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=True)
    
    with op.batch_alter_table('notification_reminders') as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False,
                   autoincrement=True)
        batch_op.alter_column('user_id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False)
    
    with op.batch_alter_table('template_group_association') as batch_op:
        batch_op.alter_column('user_template_id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=True)
        batch_op.alter_column('group_id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=True)
    
    with op.batch_alter_table('user_subscription_updates') as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False,
                   autoincrement=True)
        batch_op.alter_column('user_id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False)
    
    with op.batch_alter_table('user_usage_logs') as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False,
                   autoincrement=True)
        batch_op.alter_column('user_id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=True)
    
    with op.batch_alter_table('users_groups_association') as batch_op:
        batch_op.alter_column('user_id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False)
        batch_op.alter_column('groups_id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # CRITICAL: Reverse order - child tables BEFORE parent tables
    
    # Step 1: Child tables first
    with op.batch_alter_table('users_groups_association') as batch_op:
        batch_op.alter_column('groups_id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False)
        batch_op.alter_column('user_id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False)
    
    with op.batch_alter_table('user_usage_logs') as batch_op:
        batch_op.alter_column('user_id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=True)
        batch_op.alter_column('id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False,
                   autoincrement=True)
    
    with op.batch_alter_table('user_subscription_updates') as batch_op:
        batch_op.alter_column('user_id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False)
        batch_op.alter_column('id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False,
                   autoincrement=True)
    
    with op.batch_alter_table('template_group_association') as batch_op:
        batch_op.alter_column('group_id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=True)
        batch_op.alter_column('user_template_id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=True)
    
    with op.batch_alter_table('notification_reminders') as batch_op:
        batch_op.alter_column('user_id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False)
        batch_op.alter_column('id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False,
                   autoincrement=True)
    
    with op.batch_alter_table('node_user_usages') as batch_op:
        batch_op.alter_column('node_id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=True)
        batch_op.alter_column('user_id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False)
        batch_op.alter_column('id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False,
                   autoincrement=True)
    
    with op.batch_alter_table('node_usages') as batch_op:
        batch_op.alter_column('node_id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=True)
        batch_op.alter_column('id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False,
                   autoincrement=True)
    
    with op.batch_alter_table('node_usage_reset_logs') as batch_op:
        batch_op.alter_column('node_id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False)
        batch_op.alter_column('id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False,
                   autoincrement=True)
    
    with op.batch_alter_table('node_stats') as batch_op:
        batch_op.alter_column('node_id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False)
        batch_op.alter_column('id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False,
                   autoincrement=True)
    
    with op.batch_alter_table('next_plans') as batch_op:
        batch_op.alter_column('user_template_id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=True)
        batch_op.alter_column('user_id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False)
        batch_op.alter_column('id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False,
                   autoincrement=True)
    
    with op.batch_alter_table('inbounds_groups_association') as batch_op:
        batch_op.alter_column('group_id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False)
        batch_op.alter_column('inbound_id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False)
    
    with op.batch_alter_table('admin_usage_logs') as batch_op:
        batch_op.alter_column('admin_id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False)
        batch_op.alter_column('id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False,
                   autoincrement=True)
    
    # Step 2: Users table (before admins)
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('admin_id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=True)
        batch_op.alter_column('id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False,
                   autoincrement=True)
    
    # Step 3: Nodes table (before core_configs)
    with op.batch_alter_table('nodes') as batch_op:
        batch_op.alter_column('core_config_id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=True)
        batch_op.alter_column('id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False,
                   autoincrement=True)
    
    # Step 4: Parent tables last
    with op.batch_alter_table('system') as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False,
                   autoincrement=True)
    
    with op.batch_alter_table('settings') as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False,
                   autoincrement=True)
    
    with op.batch_alter_table('user_templates') as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False,
                   autoincrement=True)
    
    with op.batch_alter_table('inbounds') as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False,
                   autoincrement=True)
    
    with op.batch_alter_table('hosts') as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False,
                   autoincrement=True)
    
    with op.batch_alter_table('groups') as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False,
                   autoincrement=True)
    
    with op.batch_alter_table('core_configs') as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False,
                   autoincrement=True)
    
    with op.batch_alter_table('admins') as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False,
                   autoincrement=True)
    # ### end Alembic commands ###