"""admin notification enable

Revision ID: 797420faec8d
Revises: 5021dbccc95f
Create Date: 2025-11-04 18:40:23.363359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '797420faec8d'
down_revision = '5021dbccc95f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('notification_enable', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'notification_enable')
    # ### end Alembic commands ###
