"""add_wireguard_amnezia_to_hosts

Revision ID: 9cd8735ab938
Revises: b4c7e8f1a2d3
Create Date: 2026-07-12 04:18:28.202056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cd8735ab938'
down_revision = 'b4c7e8f1a2d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wireguard_amnezia', sa.JSON(none_as_null=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.drop_column('wireguard_amnezia')

    # ### end Alembic commands ###
