"""add subscription_templates to hosts

Revision ID: f1c2d3e4b5a6
Revises: ee97c01bfbaf
Create Date: 2026-02-08 00:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f1c2d3e4b5a6"
down_revision = "20e2a5cf1e40"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hosts", sa.Column("subscription_templates", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hosts", "subscription_templates")
    # ### end Alembic commands ###

