"""Human readable title and description for every generated tool, keyed by route name."""

# Off until an admin turns them on: they expose secrets, change who can do what, or wipe data in one call
DEFAULT_DISABLED_TOOLS = frozenset(
    {
        "get_settings",
        "modify_settings",
        "get_core_config",
        "create_core_config",
        "modify_core_config",
        "delete_core_config",
        "bulk_delete_cores",
        "get_node_settings",
        "create_api_key",
        "modify_api_key",
        "revoke_api_key",
        "remove_api_key",
        "bulk_delete_api_keys",
        "create_role",
        "modify_role",
        "delete_role",
        "create_admin",
        "modify_admin",
        "remove_admin",
        "bulk_delete_admins",
        "remove_all_users",
        "bulk_remove_all_users",
        "delete_expired_users",
        "reset_users_data_usage",
        "clear_usage_data",
        "modify_hosts",
    }
)

TOOL_TEXT: dict[str, tuple[str, str]] = {
    # system
    "get_system_stats": (
        "System overview",
        "Panel version, uptime, CPU/RAM/disk usage plus user counters and total traffic.",
    ),
    "get_system_resource_stats": (
        "System resources",
        "CPU, memory and disk usage of the panel host without user metrics.",
    ),
    "get_system_users_stats": (
        "User counters",
        "Total, active, online, expired, limited, on-hold and disabled user counts plus traffic totals.",
    ),
    "get_inbounds": ("List inbounds", "Inbound configurations of the cores grouped by protocol."),
    "get_inbound_details": ("List inbound tags", "Lightweight list of inbound tags with protocol and network."),
    "get_wireguard_subnets": (
        "WireGuard subnets",
        "Address usage per WireGuard subnet: capacity, used and free counts and the next free IPs.",
    ),
    "get_workers_health": ("Workers health", "Health and response time of the node and scheduler workers."),
    # users
    "get_users": (
        "List users",
        "Search and page through users. Filters: search, status, owner, groups, expiry and traffic ranges.",
    ),
    "get_users_simple": ("List users (ids only)", "Lightweight id and username list for lookups and dropdowns."),
    "get_user": ("Get user", "Full user record: limits, expiry, groups, proxy settings, subscription URL and links."),
    "create_user": (
        "Create user",
        "Create a user. data_limit is in bytes (0 = unlimited), expire is ISO datetime or unix time, group_ids selects inbounds.",
    ),
    "create_user_from_template": (
        "Create user from template",
        "Create a user with the limits, expiry and groups of a user template.",
    ),
    "modify_user": ("Update user", "Change fields of a user. Only the fields sent are changed."),
    "modify_user_with_template": (
        "Apply template to user",
        "Reapply a user template's limits and groups to an existing user.",
    ),
    "set_user_disabled": ("Enable or disable user", "Disable a user (cuts connections) or enable it again."),
    "remove_user": ("Delete user", "Permanently delete a user."),
    "reset_user_data_usage": ("Reset user traffic", "Set the user's consumed traffic back to zero."),
    "revoke_user_subscription": (
        "Revoke user subscription",
        "Regenerate the subscription link and proxy credentials; old client configs stop working.",
    ),
    "active_next_plan": ("Activate next plan", "Apply the user's queued next plan now."),
    "set_owner": ("Change user owner", "Move a user to another admin."),
    "get_user_usage": ("User traffic history", "Traffic of one user bucketed by period, optionally per node."),
    "get_users_usage": ("Users traffic history", "Traffic of all visible users bucketed by period."),
    "get_users_count_metric": ("User count metric", "Time series of one user metric (online, expired, limited, …)."),
    "get_user_sub_update_list": (
        "Subscription fetch log",
        "Recent subscription fetches of a user with client agent and time.",
    ),
    "get_users_sub_update_chart": (
        "Subscription client chart",
        "Distribution of subscription client apps over a period.",
    ),
    "get_user_subscription_by_id": (
        "Subscription config",
        "Subscription content of a user rendered for a client type (v2ray, clash, sing-box, …).",
    ),
    "get_expired_users": (
        "List expired users",
        "Users that match the cleanup rules (expired or limited before a date).",
    ),
    "delete_expired_users": ("Delete expired users", "Delete users that match the cleanup rules. Irreversible."),
    "reset_users_data_usage": ("Reset all users traffic", "Set consumed traffic of every visible user back to zero."),
    "bulk_delete_users": ("Bulk delete users", "Delete the users with the given ids."),
    "bulk_disable_users": ("Bulk disable users", "Disable the users with the given ids."),
    "bulk_enable_users": ("Bulk enable users", "Enable the users with the given ids."),
    "bulk_reset_users_data_usage": ("Bulk reset traffic", "Reset consumed traffic of the users with the given ids."),
    "bulk_revoke_users_subscription": (
        "Bulk revoke subscriptions",
        "Regenerate subscription links of the users with the given ids.",
    ),
    "bulk_set_owner": ("Bulk change owner", "Move the users with the given ids to another admin."),
    "bulk_create_users_from_template": (
        "Bulk create from template",
        "Create many users from a template with a username pattern.",
    ),
    "bulk_apply_template_to_users": ("Bulk apply template", "Reapply a user template to the users with the given ids."),
    "bulk_modify_users_expire": ("Bulk shift expiry", "Add or subtract time from the expiry of the selected users."),
    "bulk_modify_users_datalimit": (
        "Bulk shift data limit",
        "Add or subtract bytes from the data limit of the selected users.",
    ),
    "bulk_modify_users_proxy_settings": ("Bulk update proxy settings", "Change proxy settings of the selected users."),
    # admins
    "get_current_admin": ("Current admin", "The admin this session is authenticated as, with role and permissions."),
    "get_admins": ("List admins", "Admins with role, status, user count and traffic totals."),
    "get_admins_simple": ("List admins (ids only)", "Lightweight id and username list of admins."),
    "get_admin_usage": ("Admin traffic history", "Traffic of an admin's users bucketed by period."),
    "create_admin": ("Create admin", "Create an admin with a role, password and optional limits."),
    "modify_admin": ("Update admin", "Change an admin's role, password, status, limits or notes."),
    "remove_admin": ("Delete admin", "Delete an admin. Its users must be moved or removed first."),
    "reset_admin_usage": ("Reset admin traffic", "Reset the traffic counter of an admin."),
    "disable_all_active_users": ("Disable admin's users", "Disable every active user owned by an admin."),
    "activate_all_disabled_users": ("Enable admin's users", "Re-enable every disabled user owned by an admin."),
    "remove_all_users": ("Delete admin's users", "Delete every user owned by an admin. Irreversible."),
    "bulk_delete_admins": ("Bulk delete admins", "Delete the admins with the given ids."),
    "bulk_disable_admins": ("Bulk disable admins", "Disable the admins with the given ids."),
    "bulk_enable_admins": ("Bulk enable admins", "Enable the admins with the given ids."),
    "bulk_reset_admins_usage": ("Bulk reset admin traffic", "Reset traffic counters of the admins with the given ids."),
    "bulk_disable_all_active_users": ("Bulk disable admins' users", "Disable all users of the selected admins."),
    "bulk_activate_all_disabled_users": ("Bulk enable admins' users", "Re-enable all users of the selected admins."),
    "bulk_remove_all_users": ("Bulk delete admins' users", "Delete all users of the selected admins. Irreversible."),
    # admin roles
    "get_roles": ("List roles", "Admin roles with their permissions, limits and features."),
    "get_roles_simple": ("List roles (ids only)", "Lightweight id and name list of roles."),
    "get_role": ("Get role", "Full definition of one role."),
    "create_role": ("Create role", "Create a role with a permission map, limits and access rules. Owner only."),
    "modify_role": ("Update role", "Change a role. The owner role cannot be changed. Owner only."),
    "delete_role": ("Delete role", "Delete a role that is not built in and not assigned. Owner only."),
    # api keys
    "list_api_keys": ("List API keys", "API keys with owner, status and expiry. Secrets are never returned."),
    "get_api_key": ("Get API key", "Details of one API key without its secret."),
    "create_api_key": ("Create API key", "Create an API key; the secret is returned once."),
    "modify_api_key": ("Update API key", "Change name, note, expiry, status or permissions of an API key."),
    "revoke_api_key": ("Rotate API key", "Invalidate the current secret and issue a new one."),
    "remove_api_key": ("Delete API key", "Delete an API key."),
    "bulk_delete_api_keys": ("Bulk delete API keys", "Delete the API keys with the given ids."),
    # nodes
    "get_nodes": ("List nodes", "Nodes with status, core versions, traffic counters and limits."),
    "get_nodes_simple": ("List nodes (ids only)", "Lightweight id and name list of nodes."),
    "get_node": ("Get node", "Full record of one node."),
    "get_node_settings": ("Node settings", "Global node settings, including the certificate nodes must trust."),
    "create_node": ("Create node", "Register a node by address, ports, connection type, core config and API key."),
    "modify_node": ("Update node", "Change a node's address, ports, limits, core config or status."),
    "remove_node": ("Delete node", "Delete a node and stop serving it."),
    "reconnect_node": ("Reconnect node", "Force the panel to reconnect to a node."),
    "reconnect_all_node": ("Reconnect all nodes", "Reconnect every node, or the nodes of one core."),
    "sync_node": ("Sync node users", "Push the current user list to a node, optionally flushing it first."),
    "update_node": ("Update node software", "Update the node agent on the node."),
    "update_core": ("Update node core", "Install or update the core (xray, sing-box, …) on a node."),
    "update_geofiles": ("Update node geofiles", "Update geoip/geosite files on a node."),
    "reset_node_usage": ("Reset node traffic", "Reset uplink and downlink counters of a node."),
    "get_usage": ("Nodes traffic history", "Traffic per node bucketed by period."),
    "get_node_stats_periodic": ("Node resource history", "CPU, memory and bandwidth of a node bucketed by period."),
    "realtime_node_stats": ("Node realtime stats", "Live CPU, memory, bandwidth and uptime of a connected node."),
    "realtime_nodes_stats": ("All nodes realtime stats", "Live resource usage of every connected node."),
    "node_outbounds_latency": ("Node outbound latency", "Latency check of one or all outbounds of a node."),
    "get_user_count_metric": ("Node user count metric", "Time series of a user metric measured on nodes."),
    "user_online_stats": ("User online stats on node", "Online connections of a user on one node."),
    "user_online_ip_list": ("User IPs on node", "IP addresses a user is connected from on one node."),
    "user_online_ip_list_all_nodes": (
        "User IPs on all nodes",
        "IP addresses a user is connected from across all nodes.",
    ),
    "clear_usage_data": (
        "Clear usage history",
        "Delete stored usage rows of one table within a date range. Irreversible.",
    ),
    "bulk_delete_nodes": ("Bulk delete nodes", "Delete the nodes with the given ids."),
    "bulk_disable_nodes": ("Bulk disable nodes", "Disable the nodes with the given ids."),
    "bulk_enable_nodes": ("Bulk enable nodes", "Enable the nodes with the given ids."),
    "bulk_reset_nodes_usage": ("Bulk reset node traffic", "Reset traffic counters of the nodes with the given ids."),
    "bulk_reconnect_nodes": ("Bulk reconnect nodes", "Reconnect the nodes with the given ids."),
    "bulk_update_nodes": ("Bulk update node software", "Update the node agent on the nodes with the given ids."),
    # cores
    "get_all_cores": ("List cores", "Core configurations with id, name and type."),
    "get_cores_simple": ("List cores (ids only)", "Lightweight id, name and type list of cores."),
    "get_core_config": ("Get core", "Full configuration JSON of one core."),
    "create_core_config": ("Create core", "Create a core configuration (xray, sing-box, …) from JSON."),
    "modify_core_config": ("Update core", "Replace a core configuration and optionally restart its nodes."),
    "delete_core_config": ("Delete core", "Delete a core configuration that no node uses."),
    "restart_core": ("Restart core nodes", "Restart every node that runs this core."),
    "scan_reality_target": (
        "Scan Reality target",
        "Check a domain as a Reality destination and return its TLS details.",
    ),
    "bulk_delete_cores": ("Bulk delete cores", "Delete the cores with the given ids."),
    # hosts
    "get_hosts": ("List hosts", "Proxy hosts with address, port, inbound tag and TLS settings."),
    "get_host": ("Get host", "Full record of one host."),
    "create_host": ("Create host", "Add a host (address, port, inbound tag, security settings)."),
    "modify_host": ("Update host", "Change one host."),
    "modify_hosts": ("Replace all hosts", "Replace the whole host list and apply it."),
    "remove_host": ("Delete host", "Delete a host."),
    "bulk_delete_hosts": ("Bulk delete hosts", "Delete the hosts with the given ids."),
    "bulk_disable_hosts": ("Bulk disable hosts", "Disable the hosts with the given ids."),
    "bulk_enable_hosts": ("Bulk enable hosts", "Enable the hosts with the given ids."),
    # groups
    "get_all_groups": ("List groups", "Groups with their inbound tags and user counts."),
    "get_groups_simple": ("List groups (ids only)", "Lightweight id and name list of groups."),
    "get_group": ("Get group", "Full record of one group."),
    "create_group": ("Create group", "Create a group of inbound tags."),
    "modify_group": ("Update group", "Change a group's name or inbound tags."),
    "remove_group": ("Delete group", "Delete a group."),
    "bulk_add_groups_to_users": ("Add groups to users", "Add groups to the selected users."),
    "bulk_remove_users_from_groups": ("Remove groups from users", "Remove groups from the selected users."),
    "bulk_delete_groups": ("Bulk delete groups", "Delete the groups with the given ids."),
    "bulk_disable_groups": ("Bulk disable groups", "Disable the groups with the given ids."),
    "bulk_enable_groups": ("Bulk enable groups", "Enable the groups with the given ids."),
    # user templates
    "get_user_templates": ("List user templates", "User templates with limits, expiry and groups."),
    "get_user_templates_simple": ("List user templates (ids only)", "Lightweight id and name list of user templates."),
    "get_user_template": ("Get user template", "Full record of one user template."),
    "create_user_template": ("Create user template", "Create a template of data limit, expiry and groups."),
    "modify_user_template": ("Update user template", "Change a user template."),
    "remove_user_template": ("Delete user template", "Delete a user template."),
    "bulk_delete_user_templates": ("Bulk delete user templates", "Delete the user templates with the given ids."),
    "bulk_disable_user_templates": ("Bulk disable user templates", "Disable the user templates with the given ids."),
    "bulk_enable_user_templates": ("Bulk enable user templates", "Enable the user templates with the given ids."),
    # client templates
    "get_client_templates": ("List client templates", "Subscription templates for client apps."),
    "get_client_templates_simple": (
        "List client templates (ids only)",
        "Lightweight id and name list of client templates.",
    ),
    "get_client_template": ("Get client template", "Full record of one client template."),
    "create_client_template": ("Create client template", "Create a subscription template for a client type."),
    "modify_client_template": ("Update client template", "Change a client template."),
    "remove_client_template": ("Delete client template", "Delete a client template."),
    "bulk_delete_client_templates": ("Bulk delete client templates", "Delete the client templates with the given ids."),
    # hwid
    "get_user_hwids": ("List user devices", "Hardware ids registered by a user's devices."),
    "delete_user_hwid": ("Remove user device", "Remove one hardware id from a user."),
    "reset_user_hwids": ("Reset user devices", "Remove all hardware ids of a user."),
    # settings
    "get_settings": (
        "Get settings",
        "All panel settings (telegram, webhook, notifications, subscription, HWID, general).",
    ),
    "get_general_settings": ("Get general settings", "General settings such as the default encryption method."),
    "modify_settings": ("Update settings", "Change panel settings. Only the sections sent are changed."),
}
