name: Code Format Checker
on:
    push:
        branches:
            - "*"
        paths:
            - "**/*.py"

    pull_request:
        branches:
            - "*"
        paths:
            - "**/*.py"

jobs:
    ruff:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Run Ruff check
              uses: astral-sh/ruff-action@v3
              with:
                  args: check --respect-gitignore --config pyproject.toml --output-format=github .
